##   Numpy Array and Basics 

In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

Creating Array from List


In [1]:
arr_1d = np.array([1,2,3,4,5])
print("1d Array" , arr_1d )

arr_2d = np.array([[1,2,3], [5,6,7]])
print("2d Array" , arr_2d )


NameError: name 'np' is not defined

## List vs Numpy array

In [3]:
py_list = [1,2,3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1,2,3])
print("Numpy Array Multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(10000000) * 2
print("\n Array operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Numpy Array Multiplication  [2 4 6]

 List operation time:  0.19714999198913574

 Array operation time:  0.025011062622070312


## Creating array from Scretch

In [ ]:
zeros = np.zeros((5,6))
print("zeros array : \n" , zeros)

ones = np.ones((6,7))
print("Ones array : \n" , ones)

full = np.full((2,5),7)
print("Full Array : \n", full)

random = np.random.random((3,4))
print("Random Array : \n", random)

sequence = np.arange(0,20,2)
print("Sequence array : \n" , sequence)

## Vector and Matrix and Tensor

In [ ]:
vector = np.array([4,5,6,7])
print("Vector : \n", vector)

matrix = np.array([[5,6,2],
                   [5,7,9],
                   [1,2,3]])
print("Matrix : \n ", matrix)

tensor = np.array([[[12,43,54],[4,7,9]],
                   [[9,6,3],[4,7,12]]])
print("Tensor : \n", tensor)

## Array properties

In [ ]:
array = np.array([[4,5,6],
                  [1,2,3]])
print("Shape", array.shape)
print("Dimension", array.ndim)
print("Size", array.size)
print("Data Type", array.dtype)




# Array Reshaping

In [49]:
arr = np.arange(12)
print("Original Array", arr)

reshaping = arr.reshape((3,4))
print("Reshaped Array ",reshaping)

faltened = reshaping.flatten()
print("\n Flattened Array : ", faltened)

# Ravel method returns view instead of copy
raveled = reshaping.ravel()
print("\nRaveled : ", raveled)

# Transpose
transpose = reshaping.T
print("\nTranspose array : ", transpose)


Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
