## Numpy Array Operations

In [1]:
import numpy as np

In [4]:
arr = np.array([2,3,4,1,4,6,65,76,786,87,97,43,56,32,78])
print("Basic Slicing: ",arr[3:8])
print("With steps: ",arr[3:11:2])
# Same with negative indexing also



Basic Slicing:  [ 1  4  6 65 76]
With steps:  [ 1  6 76 87]


## With 2d array

In [16]:
arr_2d = np.array([[2,5,3,5],
                  [6,4,8,6],
                  [45,56,34,65],
                  [1,2,3,4]])
print("Specific Element: ", arr_2d[2,2])
print("Entire row: ", arr_2d[2])
print("Entire column: ", arr_2d[ :,2])


Specific Element:  34
Entire row:  [45 56 34 65]
Entire column:  [ 3  8 34  3]


# Sorting

In [23]:
unsorted = np.array([4,342,452,4512,76,1,67,3,67,8787,443,65])
print("Sorted : ", np.sort(unsorted))

arr_2d_unsorted = np.array([[9,3,7],
                            [6,5,4],
                            [0,5,4]])
print("Sorting 2d array with column : ", np.sort(arr_2d_unsorted , axis = 0))
print("Sorting 2d array with rows : ", np.sort(arr_2d_unsorted , axis = 1))


Sorted :  [   1    3    4   65   67   67   76  342  443  452 4512 8787]
Sorting 2d array with column :  [[0 3 4]
 [6 5 4]
 [9 5 7]]
Sorting 2d array with rows :  [[3 7 9]
 [4 5 6]
 [0 4 5]]


## Filtering

In [25]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = number[number % 2 == 0]
print("Even Numbers: ", even_number)

Even Numbers:  [ 2  4  6  8 10]


## Filter with mask

In [27]:
mask = number > 5
print("Number Greater than 5 : ", number[mask])

Number Greater than 5 :  [ 6  7  8  9 10]


## Fancy Indexing vs np.where() 

In [30]:
indices = [3,7,4]
print(number[indices])

where_result = np.where(number < 7)
print(where_result)
print("NP where ", number[where_result])

[4 8 5]
(array([0, 1, 2, 3, 4, 5]),)
NP where  [1 2 3 4 5 6]


In [36]:
condition_array = np.where(number > 6 , number * 2 , number * 3)
print(condition_array)

[ 3  6  9 12 15 18 14 16 18 20]


## Adding and Removing Data

In [39]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
 # combined = arr1 + arr2  Output: [5 7 9]
combined = np.concatenate((arr1,arr2))
print(combined)



[1 2 3 4 5 6]


## Array Compatibility

In [44]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,9])
print("Compatibility shapes 1 : ", a.shape == b.shape)
print("Compatibility shapes 2 : ", b.shape == c.shape)



Compatibility shapes 1 :  True
Compatibility shapes 2 :  False


## Adding New Column and Row

In [48]:
original = np.array([[2,4],
                     [6,5]])

new_row = np.array([[9,8]])
with_new_row = np.vstack((original,new_row))
print("Original  : ", original)
print("With New Row: ", with_new_row)

new_col = np.array([[10],[15]])
with_new_col = np.hstack((original,new_col))
print("Original  : ", original)
print("With New col: ", with_new_col)



Original  :  [[2 4]
 [6 5]]
With New Row:  [[2 4]
 [6 5]
 [9 8]]
Original  :  [[2 4]
 [6 5]]
With New col:  [[ 2  4 10]
 [ 6  5 15]]


## Deleting

In [52]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("New Array after Deletion: ", deleted)

New Array after Deletion:  [1 2 4 5]
